version: '2'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: mining_op
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
