mining_homepage:
    path:     /
    defaults: { _controller: MiningBundle:Home:index }

mining_new:
  path: /fleet
  defaults: { _controller: MiningBundle:Fleet:new }

mining_detail:
  path: /fleet/{hash}
  defaults: { _controller: MiningBundle:Fleet:detail }
  methods: [GET]

mining_detail_update:
  path: /fleet/{hash}
  defaults: { _controller: MiningBundle:Fleet:process }
  methods: [POST, PUT]
