mining_homepage:
    path:     /
    defaults: { _controller: MiningBundle:Mining:index }

mining_new:
  path: /new
  defaults: { _controller: MiningBundle:Mining:new }

mining_detail:
  path: /fleet/{hash}
  defaults: { _controller: MiningBundle:Mining:detail }
  methods: [GET]

mining_detail_update:
  path: /fleet/{hash}
  defaults: { _controller: MiningBundle:Mining:process }
  methods: [POST, PUT]
